server: 
    port: 8888
    contextPath:

spring:
    profiles:
        active: @spring.profiles.active@
    jackson:
        serialization.write_dates_as_timestamps: false
        deserialization.FAIL_ON_UNKNOWN_PROPERTIES: off
    messages:
        basename: i18n/messages
    datasource:
        driver-class-name: @datasource.driver@
        url: @datasource.url@
        username: @datasource.username@
        password: @datasource.password@
        test-while-idle: true
        max-wait-millis: 30000
        validation-query: 'SELECT 1'
        time-between-eviction-runs-millis: 20000
        min-evictable-idle-time-millis: 28700
    jpa:
        database-platform: @datasource.dialect@
        hibernate:
            ddl-auto: @datasource.jpa.hibernate.ddl-auto@
    show-sql: @datasource.jpa.show-sql@

logging:
  path: @logging.path@
  level:
    com.leadingsoft.tcloud: @logging.level@
    org.springframework: WARN

bizfuse:
    web:
        async:
            corePoolSize: 2
            maxPoolSize: 50
            queueCapacity: 10000
        #cors: #By default CORS are not enabled. Uncomment to enable.
            #allowed-origins: "*"
            #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
            #allowed-headers: "*"
            #exposed-headers:
            #allow-credentials: true
            #max-age: 1800
        swagger:
            title: T-Cloud Hub API
            description: T-Cloud Hub API documentation
            version: 0.0.1
            termsOfServiceUrl:
            contactName:
            contactUrl:
            contactEmail:
            license:
            licenseUrl:
            pathPatterns: /w/.*, /hub/.*, /rcs/.*
        metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
            jmx.enabled: true
            spark:
                enabled: false
                host: localhost
                port: 9999
            graphite:
                enabled: false
                host: localhost
                port: 2003
                prefix: microapp
            logs: # Reports Dropwizard metrics in the logs
                enabled: false
                reportFrequency: 60 # in seconds
        logging:
            logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
                enabled: false
                host: localhost
                port: 5000
                queueSize: 512
            spectator-metrics: # Reports Spectator Circuit Breaker metrics in the logs
                enabled: false


siteId: 1